import type{DocumentType}from"@/lib/types";
const money=(v:unknown)=>typeof v==="number"?new Intl.NumberFormat("en-MY",{style:"currency",currency:"MYR"}).format(v):"—";
const value=(c:Record<string,unknown>,k:string)=>String(c[k]??"—");
export function DocumentPreview({type,content}:{type:DocumentType;content:Record<string,unknown>}){const date=value(content,"sale_date");const buyer=value(content,"customer_name");const unit=value(content,"unit_number");const project=value(content,"project_name");if(type==="pre_booking_form")return <article className="letter"><LetterHead title="Pre-Booking Form" reference={value(content,"sale_reference")}/><div className="letter-grid"><Item label="Purchaser" text={buyer}/><Item label="IC / Passport" text={value(content,"customer_ic")}/><Item label="Project" text={project}/><Item label="Unit" text={unit}/><Item label="Unit type" text={value(content,"unit_type")}/><Item label="Floor area" text={`${value(content,"floor_area")} sq ft`}/><Item label="Purchase price" text={money(content.purchase_price)}/><Item label="Booking fee" text={money(content.booking_fee)}/></div><Signature name={value(content,"salesperson_name")} date={date}/></article>;
if(type==="acceptance_letter")return <article className="letter"><LetterHead title="Acceptance Letter" reference={value(content,"sale_reference")}/><p>{date}</p><p>Dear <b>{buyer}</b>,</p><p>We are pleased to confirm the acceptance of your purchase of <b>Unit {unit}, {project}</b> at the agreed purchase price of <b>{money(content.purchase_price)}</b>.</p><p>The Sale and Purchase Agreement value is <b>{money(content.spa_value)}</b>. This letter records the verified particulars supplied for the transaction.</p><Signature name="For Aira Property Management" date={date}/></article>;
if(type==="hovp_letter")return <article className="letter"><LetterHead title="HOVP Letter" reference={value(content,"sale_reference")}/><p>{date}</p><p>To: <b>{buyer}</b></p><p>Re: <b>Unit {unit}, {project}</b></p><p>We confirm the housing loan particulars for the above purchase. The approved/requested financing amount recorded is <b>{money(content.loan_amount)}</b>, representing <b>{value(content,"loan_percentage")}%</b> of the purchase price.</p><p>Please retain this letter with your transaction records.</p><Signature name="For Aira Property Management" date={date}/></article>;
return <article className="letter"><LetterHead title="Rebate Letter" reference={value(content,"sale_reference")}/><p>{date}</p><p>Dear <b>{buyer}</b>,</p><p>We confirm that the purchase of <b>Unit {unit}, {project}</b> carries a rebate of <b>{money(content.rebate_amount)}</b>, equivalent to <b>{value(content,"rebate_percentage")}%</b> of the purchase price.</p><p>This rebate is recorded against the verified sale snapshot referenced above.</p><Signature name="For Aira Property Management" date={date}/></article>}
function LetterHead({title,reference}:{title:string;reference:string}){return <header className="letter-head"><div className="letter-logo">A</div><div><h1>Aira Property</h1><p>{title}</p></div><small>REF<br/><b>{reference}</b></small></header>}
function Item({label,text}:{label:string;text:string}){return <div><small>{label}</small><strong>{text}</strong></div>}
function Signature({name,date}:{name:string;date:string}){return <div className="signature"><div><span/><b>{name}</b><small>Authorised signatory</small></div><div><span/><b>{date}</b><small>Date</small></div></div>}
