import type { ReactNode } from "react";
import { documentSteps } from "@/lib/templates";
import type { DocumentType } from "@/lib/types";

type Content=Record<string,unknown>;
const value=(content:Content,key:string,fallback="—")=>content[key]==null||content[key]===""?fallback:String(content[key]);
const number=(content:Content,key:string)=>typeof content[key]==="number"?content[key] as number:0;
const money=(amount:unknown)=>typeof amount==="number"?new Intl.NumberFormat("en-MY",{style:"currency",currency:"MYR"}).format(amount):"—";
const formattedDate=(input:unknown)=>typeof input==="string"&&input?new Intl.DateTimeFormat("en-MY",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${input}T00:00:00`)):"—";

export function DocumentPreview({type,content}:{type:DocumentType;content:Content}){
  if(type==="pre_booking_form")return <BookingForm content={content}/>;
  if(type==="acceptance_letter")return <AcceptanceLetter content={content}/>;
  if(type==="rebate_letter")return <RebateLetter content={content}/>;
  return <HovpLetter content={content}/>;
}

function Letter({content,title,children}:{content:Content;title:string;children:ReactNode}){return <article className="letter source-letter"><div className="source-band"><span>Step {documentSteps[content.document_type as DocumentType]||""}</span><b>{title}</b><small>Generated from approved record</small></div><CompanyHead/><p>{formattedDate(content.sale_date)}</p><p><b>{value(content,"customer_name").toUpperCase()}</b><br/>{value(content,"customer_address")}</p>{children}</article>}

function BookingForm({content}:{content:Content}){const deposit=number(content,"purchase_price")*.1;return <article className="letter source-letter booking-letter"><div className="source-band"><span>Step {documentSteps.pre_booking_form}</span><b>Aira Booking Form</b><small>Generated from POP record</small></div><CompanyHead/><h1 className="source-subject">OFFER TO PURCHASE</h1><p>Proposal date: {formattedDate(content.sale_date)}</p><Facts content={content}/><p>I/We irrevocably offer to purchase the Property described above, subject to the Sale and Purchase Agreement and other sale documents.</p><p>The earnest deposit recorded for this offer is <b>{money(content.booking_fee)}</b>. The total deposit is 10% of the purchase price, being <b>{money(deposit)}</b>.</p><p>Yours faithfully,</p><Signature name={value(content,"customer_name")} role="Purchaser"/></article>}

function AcceptanceLetter({content}:{content:Content}){const balance=Math.max(number(content,"purchase_price")*.1-number(content,"booking_fee"),0);return <Letter content={content} title="Notice of Acceptance"><p>Dear {value(content,"customer_salutation","Purchaser")} {value(content,"customer_name").split(" ")[0]},</p><h1 className="source-subject">NOTICE OF ACCEPTANCE OF OFFER TO PURCHASE</h1><Facts content={content}/><p>We are pleased to inform you that your offer to purchase the Property described above is accepted, subject to execution of the Sale and Purchase Agreement and related sale documents.</p><p>Please contact {value(content,"salesperson_name","our sales team")} to arrange execution within fourteen (14) days from receipt of this letter.</p><p>Please bring a cheque or bank draft in favour of Selangor Properties Sdn Bhd for <b>{money(balance)}</b>, being the balance deposit.</p><ApprovalSignature content={content}/></Letter>}

function RebateLetter({content}:{content:Content}){return <Letter content={content} title="Rebate Letter"><p>Dear {value(content,"customer_salutation","Purchaser")} {value(content,"customer_name").split(" ")[0]},</p><h1 className="source-subject">AIRA RESIDENCE UNIT {value(content,"unit_number")}<br/>CONFIRMATION OF REBATE OFFER</h1><p>Thank you for taking the next step towards completing your purchase of the above unit.</p><p>The rebate offered for this purchase will be recorded in the executed sale documents and applied in accordance with their terms.</p><p>Once again, congratulations on becoming part of the AIRA family.</p><ApprovalSignature content={content}/></Letter>}

function HovpLetter({content}:{content:Content}){const handover=value(content,"hovp_date","To be confirmed");return <Letter content={content} title="HOVP Letter"><p>Dear Sir or Madam,</p><h1 className="source-subject">AIRA RESIDENCE — HANDOVER OF VACANT POSSESSION</h1><p>We refer to your purchase of Unit <b>{value(content,"unit_number")}</b>, AIRA Residence.</p><p>We are pleased to inform you that vacant possession is available for handover on <b>{handover}</b>.</p><p>The Unit is handed over and accepted on an “as-is, where-is” basis in accordance with the Sale and Purchase Agreement. Please contact <b>{value(content,"salesperson_name","the sales team")}</b> for handover arrangements.</p><ApprovalSignature content={content}/><section className="appendix-section"><h2 className="source-title compact">HOVP HANDOVER ACKNOWLEDGEMENT</h2><p>I/We acknowledge receipt of the keys, access cards, remote controls and applicable handover items for the above Unit.</p><div className="source-signatures"><Signature name={value(content,"customer_name")} role="Purchaser signature and date"/><ApprovalSignature content={content}/></div></section></Letter>}

function CompanyHead(){return <header className="source-letter-head"><div className="sp-mark">SP</div><div className="sp-letterhead"><b>SELANGOR PROPERTIES SDN. BHD.</b><small>Registration No. 196301000340 (5199-X)</small><em>AIRA RESIDENCE</em><small>Level 3, Block D, The Five @ KPD, Kompleks Pejabat Damansara, Damansara Heights, 50490 Kuala Lumpur</small></div></header>}
function Facts({content}:{content:Content}){return <dl className="source-grid letter-facts"><Fact label="Project">{value(content,"project_name")}</Fact><Fact label="Property">Parcel No. {value(content,"unit_number")}</Fact><Fact label="Purchaser">{value(content,"customer_name")}</Fact><Fact label="Purchase price">{money(content.purchase_price)}</Fact></dl>}
function Fact({label,children}:{label:string;children:ReactNode}){return <div><dt>{label}</dt><dd>{children}</dd></div>}
function Signature({name,role}:{name:string;role:string}){return <div><span/><b>{name}</b><small>{role}</small></div>}
function ApprovalSignature({content}:{content:Content}){const name=value(content,"authorised_signatory_name","");const designation=value(content,"authorised_signatory_position","");return <div className="approval-signature"><span/><small>Name: {name||"__________________________________"}</small><small>Designation: {designation||"____________________________"}</small><small>For Selangor Properties Sdn. Bhd.</small></div>}
