"use client";
import { useActionState } from "react";
import { saveSale,type FormState } from "@/lib/actions/sales";
import type { Sale } from "@/lib/types";
const Field=({name,label,type="text",required=false,wide=false,defaultValue,error}:{name:string;label:string;type?:string;required?:boolean;wide?:boolean;defaultValue?:string|number|null;error?:string})=><div className={`field ${wide?"full":""}`}><label htmlFor={name}>{label}{required&&<span className="required"> *</span>}</label><input id={name} name={name} type={type} required={required} min={type==="number"?0:undefined} step={type==="number"?"0.01":undefined} defaultValue={defaultValue??""} aria-invalid={!!error} aria-describedby={error?`${name}-error`:undefined}/>{error&&<p className="error" id={`${name}-error`}>{error}</p>}</div>;
const SelectField=({name,label,defaultValue,options}:{name:string;label:string;defaultValue?:string|number|boolean|null;options:Array<[string,string]>})=><div className="field"><label htmlFor={name}>{label}</label><select id={name} name={name} defaultValue={defaultValue==null?"":String(defaultValue)}><option value="">Select</option>{options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>;
export function SaleForm({sale}:{sale?:Sale}){const[state,action,pending]=useActionState<FormState,FormData>(saveSale,{});const v=(key:keyof Sale):string|number=>{const raw=state.fields?.[key]??sale?.[key];return typeof raw==="number"?raw:raw==null?"":String(raw)};return <form action={action} className="card form-card">{sale&&<input type="hidden" name="id" value={sale.id}/>} {state.error&&<div className="alert">{state.error}</div>}
<section className="form-section"><div className="section-heading"><div><p className="eyebrow">Booking form</p><h2>Purchaser particulars</h2></div><span className="template-step">Step 1 source fields</span></div><div className="form-grid"><SelectField name="customer_salutation" label="Salutation" defaultValue={v("customer_salutation")} options={[["Mr","Mr"],["Ms","Ms"],["Mrs","Mrs"],["Dr","Dr"],["Company","Company"]]}/><Field name="customer_name" label="Purchaser 1 full name" required defaultValue={v("customer_name")} error={state.fieldErrors?.customer_name}/><Field name="customer_ic" label="Purchaser 1 IC / Passport / Company No." defaultValue={v("customer_ic")}/><Field name="customer_name_2" label="Purchaser 2 full name" defaultValue={v("customer_name_2") as string}/><Field name="customer_ic_2" label="Purchaser 2 IC / Passport" defaultValue={v("customer_ic_2") as string}/><Field name="customer_tin" label="TIN number" defaultValue={v("customer_tin") as string}/><Field name="customer_nationality" label="Nationality" defaultValue={v("customer_nationality") as string}/><SelectField name="customer_sex" label="Sex" defaultValue={v("customer_sex")} options={[["Female","Female"],["Male","Male"]]}/><Field name="customer_race" label="Race" defaultValue={v("customer_race") as string}/><SelectField name="bumi_status" label="Bumiputera status" defaultValue={v("bumi_status")} options={[["true","Yes"],["false","No"]]}/><Field name="customer_occupation" label="Occupation" defaultValue={v("customer_occupation") as string}/><Field name="contact_person" label="Contact person" defaultValue={v("contact_person") as string}/><Field name="customer_phone" label="Mobile number" defaultValue={v("customer_phone")}/><Field name="customer_email" label="Email" type="email" defaultValue={v("customer_email")} error={state.fieldErrors?.customer_email}/><Field name="customer_address" label="Correspondence address" wide defaultValue={v("customer_address")}/></div></section>
<section className="form-section"><h2>Property details</h2><div className="form-grid"><Field name="project_name" label="Project" required defaultValue={v("project_name")} error={state.fieldErrors?.project_name}/><Field name="unit_number" label="Parcel / unit number" defaultValue={v("unit_number")}/><Field name="storey_number" label="Storey number" defaultValue={v("storey_number") as string}/><Field name="unit_type" label="Unit type" defaultValue={v("unit_type")}/><Field name="floor_area" label="Area (sq ft)" type="number" defaultValue={v("floor_area")} error={state.fieldErrors?.floor_area}/><Field name="floor_area_sqm" label="Area (sq m)" type="number" defaultValue={v("floor_area_sqm") as number|null} error={state.fieldErrors?.floor_area_sqm}/><Field name="car_parking_bay" label="Car parking bay" defaultValue={v("car_parking_bay") as string}/></div></section>
<section className="form-section"><h2>Pricing & financing</h2><div className="form-grid"><Field name="purchase_price" label="Purchase price (RM)" type="number" required defaultValue={v("purchase_price")} error={state.fieldErrors?.purchase_price}/><Field name="booking_fee" label="Booking fee (RM)" type="number" defaultValue={v("booking_fee")} error={state.fieldErrors?.booking_fee}/><Field name="spa_value" label="SPA value (RM)" type="number" defaultValue={v("spa_value")} error={state.fieldErrors?.spa_value}/><Field name="loan_amount" label="Loan amount (RM)" type="number" defaultValue={v("loan_amount")} error={state.fieldErrors?.loan_amount}/><Field name="rebate_amount" label="Rebate amount (RM)" type="number" defaultValue={v("rebate_amount")} error={state.fieldErrors?.rebate_amount}/></div></section>
<section className="form-section"><h2>Sale administration</h2><div className="form-grid"><Field name="sale_reference" label="Sale reference (auto if blank)" defaultValue={v("sale_reference")}/><Field name="salesperson_name" label="Salesperson / agent" defaultValue={v("salesperson_name")}/><Field name="agent_company" label="Agent company" defaultValue={v("agent_company") as string}/><Field name="proprietor_name" label="Proprietor" defaultValue={v("proprietor_name") as string}/><Field name="solicitor_name" label="Solicitor / copy recipient" defaultValue={v("solicitor_name") as string}/><Field name="authorised_signatory_name" label="Authorised signatory" defaultValue={v("authorised_signatory_name") as string}/><Field name="authorised_signatory_position" label="Signatory position" defaultValue={v("authorised_signatory_position") as string}/><Field name="sale_date" label="Offer / sale date" type="date" defaultValue={v("sale_date")}/></div></section>
<div className="form-actions"><button className="button" disabled={pending}>{pending?"Saving…":sale?"Save changes":"Save draft"}</button></div></form>}
