"use client";
import { useActionState } from "react";
import { saveSale,type FormState } from "@/lib/actions/sales";
import type { Sale } from "@/lib/types";
const Field=({name,label,type="text",required=false,wide=false,defaultValue,error}:{name:string;label:string;type?:string;required?:boolean;wide?:boolean;defaultValue?:string|number|null;error?:string})=><div className={`field ${wide?"full":""}`}><label htmlFor={name}>{label}{required&&<span className="required"> *</span>}</label><input id={name} name={name} type={type} required={required} min={type==="number"?0:undefined} step={type==="number"?"0.01":undefined} defaultValue={defaultValue??""} aria-invalid={!!error} aria-describedby={error?`${name}-error`:undefined}/>{error&&<p className="error" id={`${name}-error`}>{error}</p>}</div>;
export function SaleForm({sale}:{sale?:Sale}){const[state,action,pending]=useActionState<FormState,FormData>(saveSale,{});const v=(key:keyof Sale)=>state.fields?.[key]??sale?.[key]??"";return <form action={action} className="card form-card">{sale&&<input type="hidden" name="id" value={sale.id}/>} {state.error&&<div className="alert">{state.error}</div>}
<section className="form-section"><h2>Buyer details</h2><div className="form-grid"><Field name="customer_name" label="Full name" required defaultValue={v("customer_name")} error={state.fieldErrors?.customer_name}/><Field name="customer_ic" label="IC / Passport" defaultValue={v("customer_ic")}/><Field name="customer_phone" label="Phone" defaultValue={v("customer_phone")}/><Field name="customer_email" label="Email" type="email" defaultValue={v("customer_email")} error={state.fieldErrors?.customer_email}/><Field name="customer_address" label="Address" wide defaultValue={v("customer_address")}/></div></section>
<section className="form-section"><h2>Property</h2><div className="form-grid"><Field name="project_name" label="Project" required defaultValue={v("project_name")} error={state.fieldErrors?.project_name}/><Field name="unit_number" label="Unit number" defaultValue={v("unit_number")}/><Field name="unit_type" label="Unit type" defaultValue={v("unit_type")}/><Field name="floor_area" label="Floor area (sq ft)" type="number" defaultValue={v("floor_area")} error={state.fieldErrors?.floor_area}/></div></section>
<section className="form-section"><h2>Pricing & financing</h2><div className="form-grid"><Field name="purchase_price" label="Purchase price (RM)" type="number" required defaultValue={v("purchase_price")} error={state.fieldErrors?.purchase_price}/><Field name="booking_fee" label="Booking fee (RM)" type="number" defaultValue={v("booking_fee")} error={state.fieldErrors?.booking_fee}/><Field name="spa_value" label="SPA value (RM)" type="number" defaultValue={v("spa_value")} error={state.fieldErrors?.spa_value}/><Field name="loan_amount" label="Loan amount (RM)" type="number" defaultValue={v("loan_amount")} error={state.fieldErrors?.loan_amount}/><Field name="rebate_amount" label="Rebate amount (RM)" type="number" defaultValue={v("rebate_amount")} error={state.fieldErrors?.rebate_amount}/></div></section>
<section className="form-section"><h2>Sale administration</h2><div className="form-grid"><Field name="sale_reference" label="Sale reference (auto if blank)" defaultValue={v("sale_reference")}/><Field name="salesperson_name" label="Salesperson" defaultValue={v("salesperson_name")}/><Field name="sale_date" label="Sale date" type="date" defaultValue={v("sale_date")}/></div></section>
<div className="form-actions"><button className="button" disabled={pending}>{pending?"Saving…":sale?"Save changes":"Save draft"}</button></div></form>}
