import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import type { DocumentType } from "@/lib/types";

const text=(content:Record<string,unknown>,key:string,fallback="—")=>content[key]==null||content[key]===""?fallback:String(content[key]);
const amount=(value:unknown)=>typeof value==="number"?new Intl.NumberFormat("en-MY",{style:"currency",currency:"MYR"}).format(value):"—";
const date=(value:unknown)=>{if(typeof value!=="string"||!value)return "—";return new Intl.DateTimeFormat("en-MY",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${value}T00:00:00`));};
const line=(value:string)=>new Paragraph({children:[new TextRun(value)]});

export async function createWordLetter(type:DocumentType,content:Record<string,unknown>){
  const purchaser=text(content,"customer_name");
  const unit=text(content,"unit_number");
  const signer=text(content,"authorised_signatory_name","");
  const designation=text(content,"authorised_signatory_position","");
  const common=[
    new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:"SELANGOR PROPERTIES SDN. BHD.",bold:true,size:26})]}),
    new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:"AIRA RESIDENCE",bold:true,size:22})]}),
    new Paragraph({children:[new TextRun(date(content.sale_date))]}),
    line(purchaser),line(text(content,"customer_address")),
  ];
  let title="";let body:string[]=[];
  if(type==="acceptance_letter"){const balance=Math.max((typeof content.purchase_price==="number"?content.purchase_price:0)*.1-(typeof content.booking_fee==="number"?content.booking_fee:0),0);const agent=[text(content,"salesperson_name","our Head of Sales"),text(content,"agent_company","")].filter(Boolean).join(" from ");title="NOTICE OF ACCEPTANCE OF OFFER TO PURCHASE";body=[`Dear ${text(content,"customer_salutation","Purchaser")} ${purchaser.split(" ")[0]},`,`Project: ${text(content,"project_name")}`,`Property: Parcel No. ${unit}${text(content,"storey_number","")?`, Tower ${text(content,"storey_number","")}`:""}`,`Vendor: Selangor Properties Sdn Bhd`,`Proprietor: ${text(content,"proprietor_name","Bangsar Hill Holdings Sdn. Bhd.")}`,`Purchaser: ${purchaser}`,`Purchase Price: ${amount(content.purchase_price)}`,`Greetings from Selangor Properties and the AIRA Residence team.`,`We thank you for your Offer to Purchase the Property described above, dated ${date(content.sale_date)} (“Offer”). We are pleased that you have made such a discerning decision to purchase a unit in this award-winning development. We encourage you to discover more of the hidden treasures that only living in the exclusive enclave of Damansara Heights can offer.`,`You are just a few steps away from owning the Property and to help you to progress the path to completing the sale and purchase documentation, we are pleased to inform you that your Offer is accepted subject to your execution of the Sale and Purchase Agreement (“SPA”), the Deed of Mutual Covenants and all other relevant documents in relation to the sale and purchase of the Property (collectively “Sale Documents”) in the manner described below.`,`As a first step, we kindly ask that you to contact our Head of Sales, your sales and marketing agent, ${agent}, to fix an appointment to execute the Sale Documents within fourteen (14) days from the date of your receipt of this Letter.`,`Secondly, to complete the sales process, please bring along the following documents during your appointment to execute the Sale Documents:`,`(1) a cheque or bank draft made in favour of “Selangor Properties Sdn Bhd” for a sum equivalent to ${amount(balance)}, being payment of the Balance Deposit of the Purchase Price as prescribed in the Sixth Schedule of the SPA; and`,`(2) your passport;`,`Once again, welcome to the AIRA Residence family - we look forward to the culmination of your purchase.`,`c.c. ${text(content,"solicitor_name","")}`];}
  if(type==="rebate_letter"){title=`AIRA RESIDENCE : UNIT ${unit} — CONFIRMATION OF REBATE OFFER`;body=[`Dear ${text(content,"customer_salutation","Purchaser")} ${purchaser.split(" ")[0]},`,`Greetings from AIRA Residence.`,`Thank you for taking the next step towards culminating your purchase of the abovementioned unit.`,`As agreed, a rebate of ${amount(content.rebate_amount)} has been approved and will be offset directly from the payment of your Balance Purchase Price that follows the signing of the Sale and Purchase Agreement (SPA) and payment of Balance Deposit under the Sixth Schedule.`,`Once again, congratulations for becoming part of the AIRA family.`];}
  if(type==="hovp_letter"){const handover=text(content,"hovp_date","To be confirmed");title="AIRA RESIDENCE — HANDOVER OF VACANT POSSESSION";body=[`Dear Sir or Madam,`,`We refer to your purchase of Unit ${unit}, AIRA Residence (“Unit”).`,`We are pleased to inform you that vacant possession of the Unit is available for handover on ${handover}.`,`The handover of the Unit shall be on the following basis:`,`As-Is, Where-Is Basis and No DLP`,`The Unit, including all fixtures, fittings, furniture, appliances and other items within the Unit, is handed over and accepted on an “as-is, where-is” basis in its existing condition at the time of handover, in accordance with the terms of the Sale and Purchase Agreement (“SPA”).`,`Handover Items`,`The applicable keys, access cards, remote controls and other handover items relating to the Unit will be handed over upon completion of the handover formalities.`,`Renovation and Alteration`,`Following handover, any renovation, alteration or modification carried out within the Unit shall be at your own cost and responsibility.`,`Building Management`,`Following handover, matters relating to the building, common areas, facilities and building management shall be referred to AIRA Building Management.`,`AIRA Building Management`,`Tel: 03-2011 5908`,`Email: airaresidencemgmt@gmail.com`,`For matters relating to the HOVP and handover arrangements, please contact:`,`Name: ${text(content,"salesperson_name","")}`,`Designation: `,`Mobile: `,`Email: `,`Please sign the HOVP Handover Acknowledgement below as confirmation of receipt and acceptance of vacant possession.`,`Thank you.`];}
  if(type==="pre_booking_form"){title="AIRA BOOKING FORM";body=[`Purchaser: ${purchaser}`,`Project: ${text(content,"project_name")}`,`Unit: ${unit}`,`Purchase price: ${amount(content.purchase_price)}`,`Earnest deposit: ${amount(content.booking_fee)}`];}
  const document=new Document({sections:[{properties:{},children:[...common,new Paragraph({heading:HeadingLevel.HEADING_1,alignment:AlignmentType.CENTER,children:[new TextRun({text:title,bold:true})]}),...body.map(line),line(""),line("Yours faithfully,"),line("For and on behalf of Selangor Properties Sdn. Bhd."),line(""),line(""),line("__________________________________"),line(`Name: ${signer||"__________________________________"}`),line(`Designation: ${designation||"____________________________"}`)]}]});
  return new Uint8Array(await Packer.toBuffer(document));
}
